version: '3'

services:

    galhardoapp_api_postgres:
        image: postgres
        container_name: galhardoapp_api_postgres
        environment:
            POSTGRES_PASSWORD: "postgres"
        ports:
            - "2222:5432"
        volumes:
            - postgres-data:/var/lib/postgresql
        networks:
            - galhardoapp_api_network

    # system: postgresql | username: postgres | password: postgres |server: galhardoapp_api_postgres
    galhardoapp_api_adminer:
        image: adminer
        container_name: galhardoapp_api_adminer
        ports:
            - "8080:8080"
        networks:
            - galhardoapp_api_network

    galhardoapp_api_rabbitmq:
        image: rabbitmq:3-management
        container_name: 'galhardoapp_api_rabbitmq'
        restart: always
        environment:
            - "RABBITMQ_DEFAULT_PASS=rabbitmq"
            - "RABBITMQ_DEFAULT_USER=rabbitmq"
        ports:
            - 5672:5672
            - 15672:15672
        networks:
            - galhardoapp_api_network

networks:
    galhardoapp_api_network:
        driver: bridge

volumes:
    postgres-data: null
